// ==========================================
// REPORTS SERVICE
// ==========================================

import { apiClient } from './apiClient';
import { GeneratedReport, ReportType } from '../types';

export const reportService = {
  /**
   * Fetches the list of generated and available intelligence reports
   */
  async getReports(): Promise<GeneratedReport[]> {
    try {
      const serverReports = await apiClient.get<GeneratedReport[]>('/reports');
      return serverReports;
    } catch {
      // Check locally generated reports in local storage
      try {
        const local = JSON.parse(localStorage.getItem('zuno_local_reports') || '[]');
        return local;
      } catch {
        return [];
      }
    }
  },

  /**
   * Requests new report generation
   */
  async generateReport(type: ReportType, title: string, organization: string): Promise<GeneratedReport> {
    const newReport: GeneratedReport = {
      id: `rep_${Date.now()}`,
      title,
      type,
      generatedAt: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
      generatedBy: 'Current User',
      organization: organization || 'National Skills Council',
      status: 'ready',
      summary: `Automated ${type.replace(/_/g, ' ')} intelligence briefing generated by Zuno Engine.`,
    };

    try {
      return await apiClient.post<GeneratedReport>('/reports/generate', { type, title, organization });
    } catch {
      const existing = JSON.parse(localStorage.getItem('zuno_local_reports') || '[]');
      existing.unshift(newReport);
      localStorage.setItem('zuno_local_reports', JSON.stringify(existing));
      return newReport;
    }
  }
};
